version: "3"
services:

  mysql:
    image: "mysql" #镜像的地址和版本
    container_name: boke_mysql
    environment:
      MYSQL_ROOT_PASSWORD: "boke" # 为数据库的密码，也就是root用户的密。
      MYSQL_PASS: 'boke' # 密码
    command: "--default-authentication-plugin=mysql_native_password "
    restart: always
    ports: #为映射端口。
      - 3306:3306
    # volumes:
    #   - ./init.sql:/data/application/init.sql  
    #   - ./mysql_data:/var/lib/mysql
  redis:
    image: redis:6.2.5
    restart: unless-stopped
    container_name: redis_boke
    command: ['--requirepass', '']
    ports: #为映射端口。
      - 6379:6379
  web:
    container_name: boke_web
    build: .
    # restart: always
    # command: python manage.py runserver 0.0.0.0:8001
    volumes:
      - .:/code
      - ./log:/root/log
    ports:
      - "8001:8001"