# Generated by Django 3.2.4 on 2022-10-23 09:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_classifymodels_tagsmodels'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagsArticleModels',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('tags_id', models.UUIDField(verbose_name='标签id')),
                ('article_id', models.UUIDField(verbose_name='文章id')),
            ],
            options={
                'verbose_name': '标签文章管理表',
                'verbose_name_plural': '标签文章管理表',
                'db_table': 'tags_article',
                'managed': True,
            },
        ),
    ]
